In [1]:
!jupyter notebook --generate-config

Writing default config to: C:\Users\Admin\.jupyter\jupyter_notebook_config.py


In [1]:
import numpy as np
np.__version__

'1.20.3'

In [2]:
np?

In [4]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [5]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [7]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [8]:
x3.ndim

3

In [9]:
x3.shape

(3, 4, 5)

In [10]:
x3.size

60

In [11]:
x3.dtype

dtype('int32')

In [12]:
x3.itemsize  # размер в байтах каждого эл-та массива

4

In [13]:
x3.nbytes  # полный размер массива в байтах

240