## Операции над массивами. Транслирование. broadcasting

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

In [3]:
a + b

array([5, 6, 7])

In [4]:
a + 5

array([5, 6, 7])

In [5]:
M = np.ones((3,3))

In [6]:
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [8]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

In [9]:
a

array([0, 1, 2])

In [10]:
b

array([[0],
       [1],
       [2]])

In [11]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [12]:
a = np.arange(3).reshape((3,1))

In [13]:
b = np.arange(3)

In [14]:
a

array([[0],
       [1],
       [2]])

In [15]:
b

array([0, 1, 2])

In [16]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### ситуация когда 2 массива несовместимы:

In [17]:
M = np.ones((3,2))

In [18]:
a = np.arange(3)

In [19]:
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
a

array([0, 1, 2])

In [21]:
a + M

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

### Транслирование на практике