In [1]:
# !jupyter notebook --generate-config

Writing default config to: C:\Users\Admin\.jupyter\jupyter_notebook_config.py


In [3]:
import numpy as np
np.__version__

'1.20.3'

In [20]:
np?

In [4]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [32]:
x1

array([5, 0, 3, 3, 7, 9])

In [22]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [23]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [24]:
x3.ndim

3

In [25]:
x3.shape

(3, 4, 5)

In [26]:
x3.size

60

In [27]:
x3.dtype

dtype('int32')

In [28]:
x3.itemsize  # размер в байтах каждого эл-та массива

4

In [29]:
x3.nbytes  # полный размер массива в байтах

240

In [34]:
x=np.arange(10)

In [35]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x[:5]

array([0, 1, 2, 3, 4])

In [37]:
x[::2]

array([0, 2, 4, 6, 8])

In [38]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
x3[::2,::2]

array([[[8, 1, 5, 9, 8],
        [5, 0, 2, 3, 8]],

       [[4, 9, 8, 1, 1],
        [7, 2, 0, 3, 5]]])

In [40]:
x2[::2,::2]

array([[3, 2],
       [1, 7]])

In [41]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [43]:
x2[:2,::2]

array([[3, 2],
       [7, 8]])

In [44]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [45]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [46]:
x2[:,0]  # первый столбец

array([3, 7, 1])

In [47]:
x2[0,:]  # первая строка

array([3, 5, 2, 4])

In [48]:
x2[0]  # первая строка

array([3, 5, 2, 4])

In [49]:
x2_sub = x2[:2,:2]

In [50]:
x2_sub

array([[3, 5],
       [7, 6]])

In [51]:
x2_sub[0,0]=99

In [52]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [53]:
x2_sub_copy = x2[:2,:2].copy()

In [54]:
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [55]:
x2_sub_copy[0,0]=1

In [56]:
x2_sub_copy

array([[1, 5],
       [7, 6]])

In [57]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [5]:
grid = np.arange(1,10,2)

In [59]:
grid

array([1, 3, 5, 7, 9])

In [6]:
grid = np.arange(1,10).reshape((3,3))

In [61]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
y = np.arange(1,5)

In [63]:
y

array([1, 2, 3, 4])

In [67]:
y.reshape(1,4)  # преобразовали в вектор-строку

array([[1, 2, 3, 4]])

In [68]:
y

array([1, 2, 3, 4])

In [69]:
y[np.newaxis,:]  # преобразовали в вектор-строку

array([[1, 2, 3, 4]])

In [70]:
y

array([1, 2, 3, 4])

In [71]:
y.reshape(4,1)  # преобразовали в вектор-столбец

array([[1],
       [2],
       [3],
       [4]])

In [72]:
y[:,np.newaxis]  # преобразовали в вектор-столбец

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
===============================================================================================================================

In [8]:
a = [1,2,3]
b = [4,5,6]

In [74]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [9]:
c = [97,98,99]

In [76]:
np.concatenate([a,b,c])

array([ 1,  2,  3,  4,  5,  6, 97, 98, 99])

In [77]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
np.concatenate([grid,grid], axis=1)  # слияние по второй оси

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [81]:
# объединение по вертикали
np.vstack([a,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
d = np.array([[1],
              [2],
              [3]])

In [85]:
# объединение по горизонтали
np.hstack([grid,d])

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

In [86]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [90]:
np.split(x3, [1,2])

[array([[[8, 1, 5, 9, 8],
         [9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8],
         [1, 3, 3, 3, 7]]]),
 array([[[0, 1, 9, 9, 0],
         [4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1]]]),
 array([[[4, 9, 8, 1, 1],
         [7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4]]])]

In [92]:
np.split(x3, [2,1])

[array([[[8, 1, 5, 9, 8],
         [9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8],
         [1, 3, 3, 3, 7]],
 
        [[0, 1, 9, 9, 0],
         [4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1]]]),
 array([], shape=(0, 4, 5), dtype=int32),
 array([[[0, 1, 9, 9, 0],
         [4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1]],
 
        [[4, 9, 8, 1, 1],
         [7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4]]])]

In [10]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
np.split(grid,[1,2])

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [107]:
np.split(grid,[3,1])

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([], shape=(0, 3), dtype=int32),
 array([[4, 5, 6],
        [7, 8, 9]])]

In [110]:
np.vsplit(grid,[1])

[array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]])]

In [111]:
np.vsplit(grid,[2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

In [113]:
np.vsplit(grid,[0])

[array([], shape=(0, 3), dtype=int32),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

In [115]:
np.vsplit(grid,[1,2]) # раздел по строкам

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [11]:
np.hsplit(grid,[1,2]) # раздел по столбцам

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]