## Выполнение вычислений над массивами NumPy

In [1]:
import numpy as np

In [9]:
np.random.seed(0)

def compute_reciprocals(arg):
    output = np.empty(len(arg))
    for i in range(len(arg)):
        output[i] = 1.0/arg[i]
    return output

arg = np.random.randint(1, 10, size=5)
print(arg)
compute_reciprocals(arg)

[6 1 4 4 8]


array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [14]:
np.empty(5)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [16]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.75 s ± 26.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Введение в универсальные ф-ии

In [17]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [18]:
x = np.arange(9).reshape([3,3])
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [19]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
Все массивы NumPy поддерживают стандартные арифметические операторы +-*/ // % ** 
они являются адаптерами для встоенных операций (методов) NumPy
+  np.add
-  np.subtract
-  np.negative (изменение знака)
*  np.multyply
/  np.divide
** np.power
abs(x)  np.absolute(x)
и т.д. стр.81
При этом операции осуществляются сразу над всем массивом #ВЕКТОРНЫЕ - быстрые
в отличии от циклов

In [20]:
np.add(x,100)

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108]])

In [21]:
x+100

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108]])

In [22]:
theta = np.linspace(0, np.pi, 3)

In [23]:
theta

array([0.        , 1.57079633, 3.14159265])

In [24]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [26]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [27]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [28]:
x = [-1,0,1]

In [29]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [31]:
x = [1,2,3]

In [32]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [33]:
np.power(5,x)

array([  5,  25, 125], dtype=int32)

In [34]:
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [36]:
np.log2(x)

array([0.       , 1.       , 1.5849625])

In [37]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125])

### Указание массива для вывода результата

In [40]:
x = np.arange(5)
y = np.empty(5)

In [41]:
np.multiply(x, 10, out=y)  # out=y Указание массива для вывода результата

array([ 0., 10., 20., 30., 40.])

In [42]:
y

array([ 0., 10., 20., 30., 40.])

In [43]:
y = np.zeros(10)

In [44]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.power(2, x, out=y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [46]:
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [47]:
z = np.power(3,x)

In [48]:
z

array([ 1,  3,  9, 27, 81], dtype=int32)

In [49]:
x[0] = 100

In [50]:
x

array([100,   1,   2,   3,   4])

In [51]:
z

array([ 1,  3,  9, 27, 81], dtype=int32)

#### reduce
##### Оператор редуцирования массива - последователное применение операции ко всем элементам пока не останется 1 эл-т

In [52]:
np.add.reduce(x)  # сумма всех эл-тов массива

110

In [53]:
np.multiply.reduce(x)  # приозведение всех эл-тов массива

2400

In [54]:
np.add.accumulate(x)  # массив из последовательно применненных операций суммирования

array([100, 101, 103, 106, 110], dtype=int32)

In [55]:
np.multiply.accumulate(z)  # массив из последовательно применненных операций произведения

array([    1,     3,    27,   729, 59049], dtype=int32)

In [57]:
np.sum(x)    # сумма всех эл-тов массива

110

In [60]:
x = np.arange(1, 10)

In [61]:
np.multiply.outer(x,x)  # .outer(x,x) применение операции * ко всем парам аргументов

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])